services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ifrs9
      POSTGRES_USER: ifrs9
      POSTGRES_PASSWORD: ifrs9
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ifrs9 -d ifrs9"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.dev
    command: >
      bash -lc "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
